apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grocy
  namespace: argocd
spec:
  destination:
    namespace: grocy
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/grocy
    repoURL: https://github.com/timholm/k8s-infrastructure
    targetRevision: HEAD
    directory:
      include: "manifests.yaml"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
