apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # MetalLB v0.14.9 installation (ARM64 compatible)
  - namespace.yaml
  - https://raw.githubusercontent.com/metallb/metallb/v0.14.9/config/manifests/metallb-native.yaml
  # IP Address Pool and L2 Advertisement
  - ipaddresspool.yaml
