apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo

# Reference upstream Argo Workflows directly
resources:
  - https://github.com/argoproj/argo-workflows/releases/download/v3.5.0/install.yaml
  - namespace.yaml
  - ingressroute.yaml
  - service-nodeport.yaml
