apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace
  - network-policies
  - envoy-gateway
  - argo-rollouts
  - cloudflare-tunnel
  - argo-workflows
  - velero
  - velero-ui
  - qnap-csi
