apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../../base/infrastructure

commonLabels:
  environment: staging

patches:
  # Staging uses same limits as base, just different namespace
  - patch: |-
      - op: replace
        path: /spec/hard/pods
        value: "40"
    target:
      kind: ResourceQuota
      name: default-quota
