---
# Traefik Config Application
# Traefik itself is managed by k3s, this just manages our IngressRoutes
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/timholm/k8s-infrastructure
    targetRevision: HEAD
    path: config/traefik
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
