apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Traefik is managed by k3s, we only manage config overlays
# IngressRoutes and Middlewares for our services
resources:
  - traefik-dashboard-ingressroute.yaml
