apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../../base/infrastructure

commonLabels:
  environment: dev

patches:
  # Override resource quota for dev (smaller limits)
  - patch: |-
      - op: replace
        path: /spec/hard/requests.cpu
        value: "2"
      - op: replace
        path: /spec/hard/requests.memory
        value: 4Gi
      - op: replace
        path: /spec/hard/limits.cpu
        value: "4"
      - op: replace
        path: /spec/hard/limits.memory
        value: 8Gi
      - op: replace
        path: /spec/hard/pods
        value: "25"
    target:
      kind: ResourceQuota
      name: default-quota
