apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Argo Workflows from upstream
  - https://github.com/argoproj/argo-workflows/releases/download/v3.5.0/install.yaml
  # Local resources
  - namespace.yaml
  - ingressroute.yaml
  - service-nodeport.yaml
