apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Traefik CRDs from upstream
  - https://raw.githubusercontent.com/traefik/traefik/v3.0/docs/content/reference/dynamic-configuration/kubernetes-crd-definition-v1.yml
  # Local resources
  - namespace.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml
